VALID_REGIONS = {
    "AFRICA",
    "EUROPE",
    "ASIA",
    "AUSTRALIA_SOUTH_PACIFIC",
    "CARIBBEAN",
    "SOUTH_AMERICA",
    "MIDDLE_EAST",
    "NORTH_AMERICA",
}

REGION_COUNTRY_MAP = {
    "NORTH_AMERICA": {"United States", "Canada", "Bermuda", "Mexico"},
    "EUROPE": {
        "United Kingdom", "Netherlands", "Switzerland", "Germany", "France",
        "Ireland", "Sweden", "Denmark", "Norway", "Greece", "Italy", "Spain",
        "Belgium", "Luxembourg", "Finland", "Guernsey", "Jersey", "Isle of Man",
        "Cyprus", "Monaco"
    },
    "ASIA": {
        "China", "Japan", "Taiwan", "Singapore", "Hong Kong", "India",
        "South Korea", "Indonesia", "Malaysia", "Thailand", "Vietnam",
        "Philippines", "Kazakhstan"
    },
    "MIDDLE_EAST": {
        "Israel", "United Arab Emirates", "Saudi Arabia", "Qatar", "Jordan", "Turkey"
    },
    "SOUTH_AMERICA": {"Brazil", "Chile", "Argentina", "Colombia", "Peru", "Uruguay"},
    "CARIBBEAN": {
        "Cayman Islands", "Bahamas", "British Virgin Islands", "Puerto Rico", "Curacao"
    },
    "AUSTRALIA_SOUTH_PACIFIC": {"Australia", "New Zealand"},
    "AFRICA": {"South Africa", "Egypt", "Nigeria"},
}

SECTORS = {
    "BASIC MATERIALS": "Basic Materials",
    "CONSUMER DISCRETIONARY": "Consumer Discretionary",
    "CONSUMER STAPLES": "Consumer Staples",
    "ENERGY": "Energy",
    "FINANCE": "Finance",
    "HEALTH CARE": "Health Care",
    "INDUSTRIALS": "Industrials",
    "MISCELLANEOUS": "Miscellaneous",
    "REAL ESTATE": "Real Estate",
    "TECHNOLOGY": "Technology",
    "TELECOMMUNICATIONS": "Telecommunications",
    "UTILITIES": "Utilities",
}

INDUSTRIES = [
    "Accident &Health Insurance",
    "Advertising",
    "Aerospace",
    "Agricultural Chemicals",
    "Air Freight/Delivery Services",
    "Aluminum",
    "Apparel",
    "Auto & Home Supply Stores",
    "Auto Manufacturing",
    "Auto Parts:O.E.M.",
    "Automotive Aftermarket",
    "Banks",
    "Beverages (Production/Distribution)",
    "Biotechnology: Biological Products (No Diagnostic Substances)",
    "Biotechnology: Commercial Physical & Biological Resarch",
    "Biotechnology: Electromedical & Electrotherapeutic Apparatus",
    "Biotechnology: In Vitro & In Vivo Diagnostic Substances",
    "Biotechnology: Laboratory Analytical Instruments",
    "Biotechnology: Pharmaceutical Preparations",
    "Blank Checks",
    "Books",
    "Broadcasting",
    "Building Materials",
    "Building Products",
    "Building operators",
    "Business Services",
    "Cable & Other Pay Television Services",
    "Catalog/Specialty Distribution",
    "Clothing/Shoe/Accessory Stores",
    "Coal Mining",
    "Commercial Banks",
    "Computer Communications Equipment",
    "Computer Manufacturing",
    "Computer Software: Prepackaged Software",
    "Computer Software: Programming Data Processing",
    "Computer peripheral equipment",
    "Construction/Ag Equipment/Trucks",
    "Consumer Electronics/Appliances",
    "Consumer Electronics/Video Chains",
    "Consumer Specialties",
    "Containers/Packaging",
    "Department/Specialty Retail Stores",
    "Diversified Commercial Services",
    "Diversified Financial Services",
    "Durable Goods",
    "EDP Services",
    "Electric Utilities: Central",
    "Electrical Products",
    "Electronic Components",
    "Electronics Distribution",
    "Engineering & Construction",
    "Environmental Services",
    "Farming/Seeds/Milling",
    "Finance Companies",
    "Finance/Investors Services",
    "Finance: Consumer Services",
    "Fluid Controls",
    "Food Chains",
    "Food Distributors",
    "Forest Products",
    "Garments and Clothing",
    "General Bldg Contractors - Nonresidential Bldgs",
    "Home Furnishings",
    "Homebuilding",
    "Hospital/Nursing Management",
    "Hotels/Resorts",
    "Industrial Machinery/Components",
    "Industrial Specialties",
    "Integrated Freight & Logistics",
    "Integrated oil Companies",
    "Investment Bankers/Brokers/Service",
    "Investment Managers",
    "Life Insurance",
    "Major Banks",
    "Major Chemicals",
    "Managed Health Care",
    "Marine Transportation",
    "Meat/Poultry/Fish",
    "Medical Electronics",
    "Medical Specialities",
    "Medical/Dental Instruments",
    "Medical/Nursing Services",
    "Medicinal Chemicals and Botanical Products",
    "Metal Fabrications",
    "Metal Mining",
    "Military/Government/Technical",
    "Mining & Quarrying of Nonmetallic Minerals (No Fuels)",
    "Misc Corporate Leasing Services",
    "Misc Health and Biotechnology Services",
    "Miscellaneous",
    "Miscellaneous manufacturing industries",
    "Motor Vehicles",
    "Movies/Entertainment",
    "Multi-Sector Companies",
    "Natural Gas Distribution",
    "Newspapers/Magazines",
    "Office Equipment/Supplies/Services",
    "Oil & Gas Production",
    "Oil Refining/Marketing",
    "Oil and Gas Field Machinery",
    "Oil/Gas Transmission",
    "Oilfield Services/Equipment",
    "Ophthalmic Goods",
    "Ordnance And Accessories",
    "Other Consumer Services",
    "Other Metals and Minerals",
    "Other Pharmaceuticals",
    "Other Specialty Stores",
    "Other Transportation",
    "Package Goods/Cosmetics",
    "Packaged Foods",
    "Paints/Coatings",
    "Paper",
    "Pharmaceuticals and Biotechnology",
    "Plastic Products",
    "Pollution Control Equipment",
    "Power Generation",
    "Precious Metals",
    "Precision Instruments",
    "Professional Services",
    "Professional and commerical equipment",
    "Property-Casualty Insurers",
    "Publishing",
    "RETAIL: Building Materials",
    "Radio And Television Broadcasting And Communications Equipment",
    "Railroads",
    "Real Estate",
    "Real Estate Investment Trusts",
    "Recreational Games/Products/Toys",
    "Rental/Leasing Companies",
    "Restaurants",
    "Retail-Auto Dealers and Gas Stations",
    "Retail-Drug Stores and Proprietary Stores",
    "Retail: Computer Software & Peripheral Equipment",
    "Savings Institutions",
    "Semiconductors",
    "Services-Misc. Amusement & Recreation",
    "Shoe Manufacturing",
    "Specialty Chemicals",
    "Specialty Foods",
    "Specialty Insurers",
    "Steel/Iron Ore",
    "Telecommunications Equipment",
    "Textiles",
    "Tools/Hardware",
    "Transportation Services",
    "Trucking Freight/Courier Services",
    "Trusts Except Educational Religious and Charitable",
    "Water Sewer Pipeline Comm & Power Line Construction",
    "Water Supply",
    "Wholesale Distributors",
]